#!/bin/bash
set -e

# Clean old builds
rm -f ../bashrc-script-custom_*.deb ../bashrc-script-custom_*.buildinfo ../bashrc-script-custom_*.changes

# Use .env variable
VERSION="1.0.4"

# Clean previous packages
/home/userdepinfo/Documents/github/moon-apt-repo/clean-pkg

# Build the package
dpkg-deb --build debian/bashrc-script-custom ../bashrc-script-custom_${VERSION}_all.deb
sudo cp ../bashrc-script-custom_${VERSION}_all.deb ../moon-apt-repo/pool/main/b/bashrc-script-custom/

echo "✓ Package créé : ../bashrc-script-custom_${VERSION}_all.deb"

# Push the new package
/home/userdepinfo/Documents/github/moon-apt-repo/push-pkg

echo "✓ Package poussé dans le dépôt moon-apt-repo"
