#!/bin/bash
set -e

# Clean old builds
rm -f ../bashrc-script-custom_*.deb ../bashrc-script-custom_*.buildinfo ../bashrc-script-custom_*.changes

# Use .env variable
VERSION="1.1.4"

# Clean previous packages
cd ../moon-apt-repo
./clean-pkg

# Build the package
cd ../bashrc-script-custom
dpkg-deb --build debian/bashrc-script-custom ../bashrc-script-custom_${VERSION}_all.deb
sudo cp ../bashrc-script-custom_${VERSION}_all.deb ../moon-apt-repo/pool/main/b/bashrc-script-custom/

echo "✓ Package créé : ../bashrc-script-custom_${VERSION}_all.deb"

# Update pkg metadata
cd ../moon-apt-repo
./update-pkg
echo "✓ Metadata du dépôt mis à jour"

# Push the new package
./push-pkg
echo "✓ Package poussé dans le dépôt moon-apt-repo"

cd ../bashrc-script-custom