#!/bin/bash

set -e

# Script exécuté avant la suppression du package

case "$1" in
    remove|upgrade|deconfigure)
        # Supprimer le lien symbolique
        if [ -L /usr/bin/bashrc-script-install ]; then
            rm -f /usr/bin/bashrc-script-install
            echo "Removed symlink: bashrc-script-install"
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0