name: Deploy APT Repo

on:
  push:
    branches:
      - prod

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y reprepro dpkg-dev debhelper gnupg curl rsync

      - name: Import GPG key
        env:
          APT_GPG_PRIVATE_KEY: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          APT_GPG_PASSPHRASE: ${{ secrets.APT_GPG_PASSPHRASE }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "$APT_GPG_PRIVATE_KEY" | gpg --batch --yes --passphrase "$APT_GPG_PASSPHRASE" --pinentry-mode loopback --import
          gpg --list-secret-keys

      - name: Compute version
        id: version
        run: |
          VERSION="1.0-$(date +%Y%m%d%H%M)-${GITHUB_SHA::7}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build .deb
        run: |
          dpkg-deb --build debian/bashrc-script-custom bashrc-script-custom_${VERSION}_all.deb

      - name: Check if .deb changed
        id: check
        run: |
          NEW_HASH=$(sha256sum bashrc-script-custom_${VERSION}_all.deb | awk '{print $1}')
          echo "NEW_HASH=$NEW_HASH" >> $GITHUB_ENV
          if [ -f last_deb_hash.txt ]; then
            OLD_HASH=$(cat last_deb_hash.txt)
            if [ "$NEW_HASH" = "$OLD_HASH" ]; then
              echo "no_change=true" >> $GITHUB_ENV
            else
              echo "no_change=false" >> $GITHUB_ENV
            fi
          else
            echo "no_change=false" >> $GITHUB_ENV
          fi

      - name: Deploy APT repo
        if: env.no_change == 'false'
        run: |
          mkdir -p apt-repo/{conf,dists,db,pool}
          cat <<EOF > apt-repo/conf/distributions
          Origin: Moon
          Label: MoonRepo
          Codename: stable
          Architectures: amd64 source
          Components: main
          Description: Moon's custom Debian repo
          EOF

          reprepro -b apt-repo -V includedeb stable bashrc-script-custom_${VERSION}_all.deb
          gpg --armor --export 3EDB17B20A46A78C68EAD27DC1A50F4F29EFDE91 > apt-repo/public.key

      - name: Push to moon-apt-repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt-repo
          publish_branch: gh-pages
          external_repository: moonlight58/moon-apt-repo
          force_orphan: true  

      - name: Save last .deb hash
        if: env.no_change == 'false'
        run: |
          echo "$NEW_HASH" > last_deb_hash.txt
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add last_deb_hash.txt
          git commit -m "Update last_deb_hash.txt"
          git push origin prod
