name: Deploy APT Repo

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Installer les dépendances nécessaires
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y reprepro dpkg-dev debhelper gnupg curl rsync

      # 3️⃣ Importer la clé GPG avec passphrase
      - name: Import GPG key
        env:
          APT_GPG_PRIVATE_KEY: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          APT_GPG_PASSPHRASE: ${{ secrets.APT_GPG_PASSPHRASE }}
        run: |
          mkdir -p ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          export GPG_TTY=$(tty)
          echo "$APT_GPG_PRIVATE_KEY" | gpg --batch --passphrase "$APT_GPG_PASSPHRASE" --pinentry-mode loopback --import

      # 4️⃣ Calculer la version
      - name: Compute version
        id: version
        run: |
          VERSION="1.0-$(date +%Y%m%d%H%M)-${GITHUB_SHA::7}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      # 5️⃣ Build le .deb depuis ton dossier Debian
      - name: Build .deb
        run: |
          dpkg-deb --build debian/bashrc-script-custom bashrc-script-custom_${VERSION}_all.deb

      # 6️⃣ Vérifier si le .deb a changé
      - name: Check if .deb changed
        id: check
        run: |
          NEW_HASH=$(sha256sum bashrc-script-custom_${VERSION}_all.deb | awk '{print $1}')
          echo "NEW_HASH=$NEW_HASH" >> $GITHUB_ENV
          if [ -f last_deb_hash.txt ]; then
            OLD_HASH=$(cat last_deb_hash.txt)
            if [ "$NEW_HASH" = "$OLD_HASH" ]; then
              echo "no_change=true" >> $GITHUB_ENV
            else
              echo "no_change=false" >> $GITHUB_ENV
            fi
          else
            echo "no_change=false" >> $GITHUB_ENV
          fi

      # 7️⃣ Déployer le dépôt APT
      - name: Deploy APT repo
        if: env.no_change == 'false'
        run: |
          mkdir -p apt-repo/{conf,dists,db,pool}
          cat <<EOF > apt-repo/conf/distributions
          Origin: Moon
          Label: MoonRepo
          Codename: stable
          Architectures: amd64 source all
          Components: main
          Description: Moon's custom Debian repo
          SignWith: 3EDB17B20A46A78C68EAD27DC1A50F4F29EFDE91
          EOF
          reprepro -b apt-repo includedeb stable bashrc-script-custom_${VERSION}_all.deb
          gpg --armor --export gael.rothlin@proton.me > apt-repo/public.key
          reprepro -b apt-repo export

      # 8️⃣ Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        if: env.no_change == 'false'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt-repo

      # 9️⃣ Sauvegarder le hash du dernier .deb
      - name: Save last .deb hash
        if: env.no_change == 'false'
        run: |
          echo "$NEW_HASH" > last_deb_hash.txt
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add last_deb_hash.txt
          git commit -m "Update last_deb_hash.txt"
          git push origin prod
